#theme: jekyll-theme-cayman
theme: minima
title: Airtable2GoogleDoc 
show_downloads: false

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"
